<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['number' => 1,   'name_arabic' => 'الفاتحة',     'total_ayahs' => 7,   'start_page' => 1,   'end_page' => 1,   'juz' => 1],
            ['number' => 2,   'name_arabic' => 'البقرة',       'total_ayahs' => 286, 'start_page' => 2,   'end_page' => 49,  'juz' => 1],
            ['number' => 3,   'name_arabic' => 'آل عمران',     'total_ayahs' => 200, 'start_page' => 50,  'end_page' => 76,  'juz' => 3],
            ['number' => 4,   'name_arabic' => 'النساء',       'total_ayahs' => 176, 'start_page' => 77,  'end_page' => 106, 'juz' => 4],
            ['number' => 5,   'name_arabic' => 'المائدة',      'total_ayahs' => 120, 'start_page' => 106, 'end_page' => 127, 'juz' => 6],
            ['number' => 6,   'name_arabic' => 'الأنعام',      'total_ayahs' => 165, 'start_page' => 128, 'end_page' => 150, 'juz' => 7],
            ['number' => 7,   'name_arabic' => 'الأعراف',      'total_ayahs' => 206, 'start_page' => 151, 'end_page' => 176, 'juz' => 8],
            ['number' => 8,   'name_arabic' => 'الأنفال',      'total_ayahs' => 75,  'start_page' => 177, 'end_page' => 186, 'juz' => 9],
            ['number' => 9,   'name_arabic' => 'التوبة',       'total_ayahs' => 129, 'start_page' => 187, 'end_page' => 207, 'juz' => 10],
            ['number' => 10,  'name_arabic' => 'يونس',         'total_ayahs' => 109, 'start_page' => 208, 'end_page' => 221, 'juz' => 11],
            ['number' => 11,  'name_arabic' => 'هود',          'total_ayahs' => 123, 'start_page' => 221, 'end_page' => 235, 'juz' => 11],
            ['number' => 12,  'name_arabic' => 'يوسف',         'total_ayahs' => 111, 'start_page' => 235, 'end_page' => 248, 'juz' => 12],
            ['number' => 13,  'name_arabic' => 'الرعد',        'total_ayahs' => 43,  'start_page' => 249, 'end_page' => 255, 'juz' => 13],
            ['number' => 14,  'name_arabic' => 'إبراهيم',      'total_ayahs' => 52,  'start_page' => 255, 'end_page' => 261, 'juz' => 13],
            ['number' => 15,  'name_arabic' => 'الحجر',        'total_ayahs' => 99,  'start_page' => 262, 'end_page' => 267, 'juz' => 14],
            ['number' => 16,  'name_arabic' => 'النحل',        'total_ayahs' => 128, 'start_page' => 267, 'end_page' => 281, 'juz' => 14],
            ['number' => 17,  'name_arabic' => 'الإسراء',      'total_ayahs' => 111, 'start_page' => 282, 'end_page' => 293, 'juz' => 15],
            ['number' => 18,  'name_arabic' => 'الكهف',        'total_ayahs' => 110, 'start_page' => 293, 'end_page' => 304, 'juz' => 15],
            ['number' => 19,  'name_arabic' => 'مريم',         'total_ayahs' => 98,  'start_page' => 305, 'end_page' => 312, 'juz' => 16],
            ['number' => 20,  'name_arabic' => 'طه',           'total_ayahs' => 135, 'start_page' => 312, 'end_page' => 321, 'juz' => 16],
            ['number' => 21,  'name_arabic' => 'الأنبياء',     'total_ayahs' => 112, 'start_page' => 322, 'end_page' => 331, 'juz' => 17],
            ['number' => 22,  'name_arabic' => 'الحج',         'total_ayahs' => 78,  'start_page' => 332, 'end_page' => 341, 'juz' => 17],
            ['number' => 23,  'name_arabic' => 'المؤمنون',     'total_ayahs' => 118, 'start_page' => 342, 'end_page' => 349, 'juz' => 18],
            ['number' => 24,  'name_arabic' => 'النور',        'total_ayahs' => 64,  'start_page' => 350, 'end_page' => 359, 'juz' => 18],
            ['number' => 25,  'name_arabic' => 'الفرقان',      'total_ayahs' => 77,  'start_page' => 359, 'end_page' => 366, 'juz' => 18],
            ['number' => 26,  'name_arabic' => 'الشعراء',      'total_ayahs' => 227, 'start_page' => 367, 'end_page' => 376, 'juz' => 19],
            ['number' => 27,  'name_arabic' => 'النمل',        'total_ayahs' => 93,  'start_page' => 377, 'end_page' => 385, 'juz' => 19],
            ['number' => 28,  'name_arabic' => 'القصص',        'total_ayahs' => 88,  'start_page' => 385, 'end_page' => 396, 'juz' => 20],
            ['number' => 29,  'name_arabic' => 'العنكبوت',     'total_ayahs' => 69,  'start_page' => 396, 'end_page' => 404, 'juz' => 20],
            ['number' => 30,  'name_arabic' => 'الروم',        'total_ayahs' => 60,  'start_page' => 404, 'end_page' => 410, 'juz' => 21],
            ['number' => 31,  'name_arabic' => 'لقمان',        'total_ayahs' => 34,  'start_page' => 411, 'end_page' => 414, 'juz' => 21],
            ['number' => 32,  'name_arabic' => 'السجدة',       'total_ayahs' => 30,  'start_page' => 415, 'end_page' => 417, 'juz' => 21],
            ['number' => 33,  'name_arabic' => 'الأحزاب',      'total_ayahs' => 73,  'start_page' => 418, 'end_page' => 427, 'juz' => 21],
            ['number' => 34,  'name_arabic' => 'سبأ',          'total_ayahs' => 54,  'start_page' => 428, 'end_page' => 434, 'juz' => 22],
            ['number' => 35,  'name_arabic' => 'فاطر',         'total_ayahs' => 45,  'start_page' => 434, 'end_page' => 440, 'juz' => 22],
            ['number' => 36,  'name_arabic' => 'يس',           'total_ayahs' => 83,  'start_page' => 440, 'end_page' => 445, 'juz' => 22],
            ['number' => 37,  'name_arabic' => 'الصافات',      'total_ayahs' => 182, 'start_page' => 446, 'end_page' => 452, 'juz' => 23],
            ['number' => 38,  'name_arabic' => 'ص',            'total_ayahs' => 88,  'start_page' => 453, 'end_page' => 458, 'juz' => 23],
            ['number' => 39,  'name_arabic' => 'الزمر',        'total_ayahs' => 75,  'start_page' => 458, 'end_page' => 467, 'juz' => 23],
            ['number' => 40,  'name_arabic' => 'غافر',         'total_ayahs' => 85,  'start_page' => 467, 'end_page' => 476, 'juz' => 24],
            ['number' => 41,  'name_arabic' => 'فصلت',         'total_ayahs' => 54,  'start_page' => 477, 'end_page' => 482, 'juz' => 24],
            ['number' => 42,  'name_arabic' => 'الشورى',       'total_ayahs' => 53,  'start_page' => 483, 'end_page' => 489, 'juz' => 25],
            ['number' => 43,  'name_arabic' => 'الزخرف',       'total_ayahs' => 89,  'start_page' => 489, 'end_page' => 495, 'juz' => 25],
            ['number' => 44,  'name_arabic' => 'الدخان',       'total_ayahs' => 59,  'start_page' => 496, 'end_page' => 498, 'juz' => 25],
            ['number' => 45,  'name_arabic' => 'الجاثية',      'total_ayahs' => 37,  'start_page' => 499, 'end_page' => 502, 'juz' => 25],
            ['number' => 46,  'name_arabic' => 'الأحقاف',      'total_ayahs' => 35,  'start_page' => 502, 'end_page' => 506, 'juz' => 26],
            ['number' => 47,  'name_arabic' => 'محمد',         'total_ayahs' => 38,  'start_page' => 507, 'end_page' => 510, 'juz' => 26],
            ['number' => 48,  'name_arabic' => 'الفتح',        'total_ayahs' => 29,  'start_page' => 511, 'end_page' => 515, 'juz' => 26],
            ['number' => 49,  'name_arabic' => 'الحجرات',      'total_ayahs' => 18,  'start_page' => 515, 'end_page' => 517, 'juz' => 26],
            ['number' => 50,  'name_arabic' => 'ق',            'total_ayahs' => 45,  'start_page' => 518, 'end_page' => 520, 'juz' => 26],
            ['number' => 51,  'name_arabic' => 'الذاريات',     'total_ayahs' => 60,  'start_page' => 520, 'end_page' => 523, 'juz' => 26],
            ['number' => 52,  'name_arabic' => 'الطور',        'total_ayahs' => 49,  'start_page' => 523, 'end_page' => 525, 'juz' => 27],
            ['number' => 53,  'name_arabic' => 'النجم',        'total_ayahs' => 62,  'start_page' => 526, 'end_page' => 528, 'juz' => 27],
            ['number' => 54,  'name_arabic' => 'القمر',        'total_ayahs' => 55,  'start_page' => 528, 'end_page' => 531, 'juz' => 27],
            ['number' => 55,  'name_arabic' => 'الرحمن',       'total_ayahs' => 78,  'start_page' => 531, 'end_page' => 534, 'juz' => 27],
            ['number' => 56,  'name_arabic' => 'الواقعة',      'total_ayahs' => 96,  'start_page' => 534, 'end_page' => 537, 'juz' => 27],
            ['number' => 57,  'name_arabic' => 'الحديد',       'total_ayahs' => 29,  'start_page' => 537, 'end_page' => 541, 'juz' => 27],
            ['number' => 58,  'name_arabic' => 'المجادلة',     'total_ayahs' => 22,  'start_page' => 542, 'end_page' => 545, 'juz' => 28],
            ['number' => 59,  'name_arabic' => 'الحشر',        'total_ayahs' => 24,  'start_page' => 545, 'end_page' => 548, 'juz' => 28],
            ['number' => 60,  'name_arabic' => 'الممتحنة',     'total_ayahs' => 13,  'start_page' => 549, 'end_page' => 551, 'juz' => 28],
            ['number' => 61,  'name_arabic' => 'الصف',         'total_ayahs' => 14,  'start_page' => 551, 'end_page' => 552, 'juz' => 28],
            ['number' => 62,  'name_arabic' => 'الجمعة',       'total_ayahs' => 11,  'start_page' => 553, 'end_page' => 554, 'juz' => 28],
            ['number' => 63,  'name_arabic' => 'المنافقون',    'total_ayahs' => 11,  'start_page' => 554, 'end_page' => 555, 'juz' => 28],
            ['number' => 64,  'name_arabic' => 'التغابن',      'total_ayahs' => 18,  'start_page' => 556, 'end_page' => 557, 'juz' => 28],
            ['number' => 65,  'name_arabic' => 'الطلاق',       'total_ayahs' => 12,  'start_page' => 558, 'end_page' => 559, 'juz' => 28],
            ['number' => 66,  'name_arabic' => 'التحريم',      'total_ayahs' => 12,  'start_page' => 560, 'end_page' => 561, 'juz' => 28],
            ['number' => 67,  'name_arabic' => 'الملك',        'total_ayahs' => 30,  'start_page' => 562, 'end_page' => 564, 'juz' => 29],
            ['number' => 68,  'name_arabic' => 'القلم',        'total_ayahs' => 52,  'start_page' => 564, 'end_page' => 566, 'juz' => 29],
            ['number' => 69,  'name_arabic' => 'الحاقة',       'total_ayahs' => 52,  'start_page' => 566, 'end_page' => 568, 'juz' => 29],
            ['number' => 70,  'name_arabic' => 'المعارج',      'total_ayahs' => 44,  'start_page' => 568, 'end_page' => 570, 'juz' => 29],
            ['number' => 71,  'name_arabic' => 'نوح',          'total_ayahs' => 28,  'start_page' => 570, 'end_page' => 571, 'juz' => 29],
            ['number' => 72,  'name_arabic' => 'الجن',         'total_ayahs' => 28,  'start_page' => 572, 'end_page' => 573, 'juz' => 29],
            ['number' => 73,  'name_arabic' => 'المزمل',       'total_ayahs' => 20,  'start_page' => 574, 'end_page' => 575, 'juz' => 29],
            ['number' => 74,  'name_arabic' => 'المدثر',       'total_ayahs' => 56,  'start_page' => 575, 'end_page' => 577, 'juz' => 29],
            ['number' => 75,  'name_arabic' => 'القيامة',      'total_ayahs' => 40,  'start_page' => 577, 'end_page' => 578, 'juz' => 29],
            ['number' => 76,  'name_arabic' => 'الإنسان',      'total_ayahs' => 31,  'start_page' => 578, 'end_page' => 580, 'juz' => 29],
            ['number' => 77,  'name_arabic' => 'المرسلات',     'total_ayahs' => 50,  'start_page' => 580, 'end_page' => 581, 'juz' => 29],
            ['number' => 78,  'name_arabic' => 'النبأ',        'total_ayahs' => 40,  'start_page' => 582, 'end_page' => 583, 'juz' => 30],
            ['number' => 79,  'name_arabic' => 'النازعات',     'total_ayahs' => 46,  'start_page' => 583, 'end_page' => 584, 'juz' => 30],
            ['number' => 80,  'name_arabic' => 'عبس',          'total_ayahs' => 42,  'start_page' => 585, 'end_page' => 585, 'juz' => 30],
            ['number' => 81,  'name_arabic' => 'التكوير',      'total_ayahs' => 29,  'start_page' => 586, 'end_page' => 586, 'juz' => 30],
            ['number' => 82,  'name_arabic' => 'الانفطار',     'total_ayahs' => 19,  'start_page' => 587, 'end_page' => 587, 'juz' => 30],
            ['number' => 83,  'name_arabic' => 'المطففين',     'total_ayahs' => 36,  'start_page' => 587, 'end_page' => 589, 'juz' => 30],
            ['number' => 84,  'name_arabic' => 'الانشقاق',     'total_ayahs' => 25,  'start_page' => 589, 'end_page' => 589, 'juz' => 30],
            ['number' => 85,  'name_arabic' => 'البروج',       'total_ayahs' => 22,  'start_page' => 590, 'end_page' => 590, 'juz' => 30],
            ['number' => 86,  'name_arabic' => 'الطارق',       'total_ayahs' => 17,  'start_page' => 591, 'end_page' => 591, 'juz' => 30],
            ['number' => 87,  'name_arabic' => 'الأعلى',       'total_ayahs' => 19,  'start_page' => 591, 'end_page' => 592, 'juz' => 30],
            ['number' => 88,  'name_arabic' => 'الغاشية',      'total_ayahs' => 26,  'start_page' => 592, 'end_page' => 592, 'juz' => 30],
            ['number' => 89,  'name_arabic' => 'الفجر',        'total_ayahs' => 30,  'start_page' => 593, 'end_page' => 594, 'juz' => 30],
            ['number' => 90,  'name_arabic' => 'البلد',        'total_ayahs' => 20,  'start_page' => 594, 'end_page' => 594, 'juz' => 30],
            ['number' => 91,  'name_arabic' => 'الشمس',        'total_ayahs' => 15,  'start_page' => 595, 'end_page' => 595, 'juz' => 30],
            ['number' => 92,  'name_arabic' => 'الليل',        'total_ayahs' => 21,  'start_page' => 595, 'end_page' => 596, 'juz' => 30],
            ['number' => 93,  'name_arabic' => 'الضحى',        'total_ayahs' => 11,  'start_page' => 596, 'end_page' => 596, 'juz' => 30],
            ['number' => 94,  'name_arabic' => 'الشرح',        'total_ayahs' => 8,   'start_page' => 596, 'end_page' => 596, 'juz' => 30],
            ['number' => 95,  'name_arabic' => 'التين',        'total_ayahs' => 8,   'start_page' => 597, 'end_page' => 597, 'juz' => 30],
            ['number' => 96,  'name_arabic' => 'العلق',        'total_ayahs' => 19,  'start_page' => 597, 'end_page' => 597, 'juz' => 30],
            ['number' => 97,  'name_arabic' => 'القدر',        'total_ayahs' => 5,   'start_page' => 598, 'end_page' => 598, 'juz' => 30],
            ['number' => 98,  'name_arabic' => 'البينة',       'total_ayahs' => 8,   'start_page' => 598, 'end_page' => 599, 'juz' => 30],
            ['number' => 99,  'name_arabic' => 'الزلزلة',      'total_ayahs' => 8,   'start_page' => 599, 'end_page' => 599, 'juz' => 30],
            ['number' => 100, 'name_arabic' => 'العاديات',     'total_ayahs' => 11,  'start_page' => 599, 'end_page' => 600, 'juz' => 30],
            ['number' => 101, 'name_arabic' => 'القارعة',      'total_ayahs' => 11,  'start_page' => 600, 'end_page' => 600, 'juz' => 30],
            ['number' => 102, 'name_arabic' => 'التكاثر',      'total_ayahs' => 8,   'start_page' => 600, 'end_page' => 600, 'juz' => 30],
            ['number' => 103, 'name_arabic' => 'العصر',        'total_ayahs' => 3,   'start_page' => 601, 'end_page' => 601, 'juz' => 30],
            ['number' => 104, 'name_arabic' => 'الهمزة',       'total_ayahs' => 9,   'start_page' => 601, 'end_page' => 601, 'juz' => 30],
            ['number' => 105, 'name_arabic' => 'الفيل',        'total_ayahs' => 5,   'start_page' => 601, 'end_page' => 601, 'juz' => 30],
            ['number' => 106, 'name_arabic' => 'قريش',         'total_ayahs' => 4,   'start_page' => 602, 'end_page' => 602, 'juz' => 30],
            ['number' => 107, 'name_arabic' => 'الماعون',      'total_ayahs' => 7,   'start_page' => 602, 'end_page' => 602, 'juz' => 30],
            ['number' => 108, 'name_arabic' => 'الكوثر',       'total_ayahs' => 3,   'start_page' => 602, 'end_page' => 602, 'juz' => 30],
            ['number' => 109, 'name_arabic' => 'الكافرون',     'total_ayahs' => 6,   'start_page' => 603, 'end_page' => 603, 'juz' => 30],
            ['number' => 110, 'name_arabic' => 'النصر',        'total_ayahs' => 3,   'start_page' => 603, 'end_page' => 603, 'juz' => 30],
            ['number' => 111, 'name_arabic' => 'المسد',        'total_ayahs' => 5,   'start_page' => 603, 'end_page' => 603, 'juz' => 30],
            ['number' => 112, 'name_arabic' => 'الإخلاص',      'total_ayahs' => 4,   'start_page' => 604, 'end_page' => 604, 'juz' => 30],
            ['number' => 113, 'name_arabic' => 'الفلق',        'total_ayahs' => 5,   'start_page' => 604, 'end_page' => 604, 'juz' => 30],
            ['number' => 114, 'name_arabic' => 'الناس',        'total_ayahs' => 6,   'start_page' => 604, 'end_page' => 604, 'juz' => 30],
        ];

        foreach ($surahs as $surah) {
            Surah::create($surah);
        }
    }
}
